<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Seção-2.1" data-toc-modified-id="Seção-2.1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Seção 2.1</a></span><ul class="toc-item"><li><span><a href="#Exercício-1" data-toc-modified-id="Exercício-1-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Exercício 1</a></span></li></ul></li><li><span><a href="#Seção-2.2-&amp;-2.3" data-toc-modified-id="Seção-2.2-&amp;-2.3-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Seção 2.2 &amp; 2.3</a></span></li><li><span><a href="#Seção-2.4" data-toc-modified-id="Seção-2.4-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Seção 2.4</a></span><ul class="toc-item"><li><span><a href="#Exercício-2" data-toc-modified-id="Exercício-2-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Exercício 2</a></span></li></ul></li><li><span><a href="#Seção-2.5" data-toc-modified-id="Seção-2.5-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Seção 2.5</a></span><ul class="toc-item"><li><span><a href="#Exercício-2" data-toc-modified-id="Exercício-2-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Exercício 2</a></span></li><li><span><a href="#Exercício-3" data-toc-modified-id="Exercício-3-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Exercício 3</a></span></li><li><span><a href="#Exercício-6" data-toc-modified-id="Exercício-6-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Exercício 6</a></span></li></ul></li></ul></div>

# Lista 2
----

Exercícios resolvidos dos capítulos 2 e 3 do livro [A Gentle Introduction to Optimization](https://www.amazon.com/Gentle-Introduction-Optimization-B-Guenin-ebook/dp/B00KL8CHHU), listados abaixo.

- Sec.2.1 (certificados): ~~1a, 1b, 1c, 1d, 2i, 2ii~~

- Sec 2.2 (forma padrão): ~~1a, 1b~~

- Sec 2.3 (iteração Simplex): ~~1a, 1b~~

- Sec 2.4 (Bases e Forma canônica): ~~1a, 1b, 1c, 1d, 2a, 2b, 3, 4,a, 4b, 4c, 4d, 5a, 5b, 5c, 5d, 5e~~

- Sec 2.5 (Simplex): ~~1a, 1b, 2a, 2b, 3,~~ 4, 5, 6a, 6b, 6c

- Sec 2.6 (Simplex 2 fases): 1a, 1b, 1c, 1d, 1e


- Sec. 3 ()

In [3]:
import numpy as np

### Seção 2.1

#### Exercício 1
(a) 

Provar que o problema é infactível

In [4]:
A = np.array([[3, 5, 6], [1, 3, -4], [-1, 1, -1]])

In [5]:
b = np.array([4, 2, -1]).reshape(3, 1)

Queremos $y$ tal que:

$\text{(i) } y^{T} A \geq \vec{0}^{T},$

$\text{(ii) } y^{T} b < 0$

In [6]:
y = np.array([1, -2, 1])

In [7]:
np.dot(y.T, A) # (i)

array([ 0,  0, 13])

In [8]:
np.dot(y.T, b) # (ii)

array([-1])

(b) 

Provar que o problema é ilimitado

In [9]:
A = np.array([[1, 0, 1, -1], 
              [0, 1, 2, -1]])

In [10]:
b = np.array([1, 2]).reshape(2, 1)

In [11]:
c = np.array([0, 0, -1, 1]).reshape(4, 1)

Queremos $x = x' + dt : Ax = b, \forall t$ tal que:

$\text{(i) } d > 0$

$\text{(ii) }c^T d \geq 0 \rightarrow d_3 < d_4$

$\text{(iii) }Ad = 0 \rightarrow d_1 + 2 d_3 = 0$

In [12]:
d = np.array([2, 1, 1, 3]).reshape(4, 1) # (i) d > 0
d

array([[2],
       [1],
       [1],
       [3]])

In [13]:
np.dot(c.T, d) # (ii) c'd > 0

array([[2]])

In [14]:
np.dot(A, d) # (iii) Ad = 0

array([[0],
       [0]])

Logo, $x = x' + dt$ é:

In [15]:
x_ = np.array([0, 0, 1, 0]).reshape(4, 1)
x_

array([[0],
       [0],
       [1],
       [0]])

In [16]:
np.dot(A, x_) == b

array([[ True],
       [ True]])

Logo, temos $x = [0, 0, 1, 0] + [2, 1, 1, 3]t$. Para a letra (d), queremos $c^T x = 5000$, logo $t = \frac{5001}{2}$:

In [17]:
x = x_ + (5001/2)*d
x

array([[5001. ],
       [2500.5],
       [2501.5],
       [7501.5]])

In [18]:
np.dot(c.T, x)

array([[5000.]])

In [19]:
np.dot(A, x) == b

array([[ True],
       [ True]])

(c)

In [20]:
A = np.array([[4, 2, 1, -6, -1], [-1, 1, -4, 1, 3], [3, -6, 5, 3, -5]])

In [21]:
b = np.array([11, -2, -10]).reshape(3, 1)

In [22]:
c = np.array([1, -2, 1, 1, 1]).reshape(5, 1)

In [23]:
d = np.array([1, 1, 1, 1, 1]).reshape(5, 1)

In [24]:
np.dot(c.T, d) # (ii) c'd > 0

array([[2]])

In [25]:
np.dot(A, d) # (iii) Ad = 0

array([[0],
       [0],
       [0]])

In [26]:
x_ = np.array([1, 3, 1, 0, 0]).reshape(5, 1)

In [27]:
np.dot(A, x_)

array([[ 11],
       [ -2],
       [-10]])

Logo, temos $x = [1, 3, 1, 0, 0] + [1, 1, 1, 1, 1]t$. Para a letra (d), queremos $c^T x = 5000$, logo $t = 2502$:

In [28]:
x = x_ + 2502*d
x

array([[2503],
       [2505],
       [2503],
       [2502],
       [2502]])

In [29]:
np.dot(c.T, x)

array([[5000]])

In [30]:
np.dot(A, x) == b

array([[ True],
       [ True],
       [ True]])

### Seção 2.2 & 2.3
No papel

### Seção 2.4

#### Exercício 2

(a)

In [31]:
A = np.array([[1, -1, 2, -1, 0], [2, 0, 1, -1, 1]])
A

array([[ 1, -1,  2, -1,  0],
       [ 2,  0,  1, -1,  1]])

In [32]:
b = np.array([[1], [-1]])
b

array([[ 1],
       [-1]])

In [33]:
c = np.array([1, -2, 0, 1, 3]).reshape(5,1)
c

array([[ 1],
       [-2],
       [ 0],
       [ 1],
       [ 3]])

In [34]:
B = [0, 3] # indexação começa em 0! B = [1, 4]

In [133]:
def canonical_form(A, b, c, B, w=0):
    """
    Passa o PL para a forma canônica: (i) A_B deve ser identidade, (ii) c_B = 0
    
    Return
    ------
    A : np.array
    b : np.array
    c : np.array
    w : int
    """

    if not np.all(c[B] != 0) or not np.all(A[:, B] != np.identity(len(B))):

        A_Binv = np.linalg.inv(A[:, B])
        y = A_Binv.T.dot(c[B])
        c = c.T - y.T.dot(A).ravel()
        c = c.T
        print(np.dot(y.T, b))
        w = w + np.dot(y.T, b)

        A = A_Binv.dot(A)
        b = A_Binv.dot(b)
        print(">> Problema canonizado!")
        return A, b, c, w

    else:
        print(">> Problema ja na forma canonica!")

In [36]:
A, b, c, w = canonical_form(A, b, c, B)

>> Problema canonizado!


In [37]:
A

array([[ 1.,  1., -1.,  0.,  1.],
       [ 0.,  2., -3.,  1.,  1.]])

In [38]:
b

array([[-2.],
       [-3.]])

In [39]:
c

array([[ 0.],
       [-5.],
       [ 4.],
       [ 0.],
       [ 1.]])

(b)

In [40]:
A = np.array([[1, -1, 2, -1, 0], [2, 0, 1, -1, 1]])
A

array([[ 1, -1,  2, -1,  0],
       [ 2,  0,  1, -1,  1]])

In [41]:
b = np.array([[1], [-1]])
b

array([[ 1],
       [-1]])

In [42]:
c = np.array([1, -2, 0, 1, 3]).reshape(5,1)
c

array([[ 1],
       [-2],
       [ 0],
       [ 1],
       [ 3]])

In [43]:
A, b, c, w = canonical_form(A, b, c, B)

>> Problema canonizado!


In [44]:
A

array([[ 1.,  1., -1.,  0.,  1.],
       [ 0.,  2., -3.,  1.,  1.]])

In [45]:
b

array([[-2.],
       [-3.]])

In [46]:
c

array([[ 0.],
       [-5.],
       [ 4.],
       [ 0.],
       [ 1.]])

### Seção 2.5

#### Exercício 2

(a)

In [134]:
A = np.array([[2,5,1,0,3,1],
             [0,2,2,-4,2,-4],
             [3,5,1,2,6,3]])

In [135]:
b = np.array([9/4,0,4]).reshape(3,1)

In [136]:
c = np.array([2,-4,1,4,8,4]).reshape(6,1)

In [137]:
B = np.array([0,2,3])

In [138]:
A_0, b_0, c_0, w_0 = canonical_form(A, b, c, B)

[[4.75]]
>> Problema canonizado!


In [139]:
A_0

array([[ 1.00000000e+00,  4.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.00000000e+00,  1.00000000e+00],
       [-4.44089210e-16, -3.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  5.00000000e+00, -1.00000000e+00],
       [-2.22044605e-16, -2.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  2.00000000e+00,  5.00000000e-01]])

In [140]:
b_0

array([[0.5  ],
       [1.25 ],
       [0.625]])

In [141]:
c_0

array([[ 0.],
       [-1.],
       [ 0.],
       [ 0.],
       [-3.],
       [ 1.]])

In [142]:
w_0

array([[4.75]])

Passo a passo:

In [130]:
A_Binv = np.linalg.inv(A[:, B])
A_Binv

array([[ 2.  , -0.5 , -1.  ],
       [-3.  ,  1.  ,  2.  ],
       [-1.5 ,  0.25,  1.  ]])

In [131]:
y = A_Binv.T.dot(c[B])
y

array([[-5.],
       [ 1.],
       [ 4.]])

In [132]:
np.dot(y.T, b)

array([[4.75]])

In [114]:
c = c.T - y.T.dot(A).ravel()
c = c.T
c

array([[ 0.],
       [-1.],
       [ 0.],
       [ 0.],
       [-3.],
       [ 1.]])

In [115]:
w = w + np.dot(y.T, b)
w

array([[5.5]])

In [116]:
A = A_Binv.dot(A)
A.round(2)

array([[ 1. ,  4. ,  0. ,  0. , -1. ,  1. ],
       [-0. , -3. ,  1. ,  0. ,  5. , -1. ],
       [-0. , -2. ,  0. ,  1. ,  2. ,  0.5]])

In [117]:
b = A_Binv.dot(b) 
b

array([[0.5  ],
       [1.25 ],
       [0.625]])

(b)

In [96]:
B_1 = np.array([2,3,5])

In [145]:
A_1, b_1, c_1, w_1 = canonical_form(A_0, b_0, c_0, B_1, w_0)

[[0.5]]
>> Problema canonizado!


In [146]:
A_1

array([[ 1. ,  1. ,  1. ,  0. ,  4. ,  0. ],
       [-0.5, -4. ,  0. ,  1. ,  2.5,  0. ],
       [ 1. ,  4. ,  0. ,  0. , -1. ,  1. ]])

In [147]:
b_1

array([[1.75 ],
       [0.375],
       [0.5  ]])

In [148]:
c_1

array([[-1.],
       [-5.],
       [ 0.],
       [ 0.],
       [-2.],
       [ 0.]])

In [149]:
w_1

array([[5.25]])

#### Exercício 3

In [150]:
A = np.array([[-2,1,1,1,0,0],
              [1,-1,0,0,1,0],
              [2,-3,-1,0,0,1]])

In [151]:
b = np.array([1,2,6]).reshape(3,1)
c = np.array([2,1,-1,0,0,0]).reshape(6,1)

In [157]:
import sys
import os
sys.path.insert(0, os.path.dirname(os.getcwd()))

In [159]:
from two_phase import simplex_two_phase

In [163]:
B = np.array([3,4,5])
S = simplex_two_phase.Simplex(A, c, b, B)

In [164]:
S.fase_2()



FASE II:

>>> Iteração 0:

1. Reescrevendo o PL na forma canonica para a base B...

A: 
 [[-2.  1.  1.  1.  0.  0.]
 [ 1. -1.  0.  0.  1.  0.]
 [ 2. -3. -1.  0.  0.  1.]]
b: 
 [[1.]
 [2.]
 [6.]]
c: 
 [[ 2.]
 [ 1.]
 [-1.]
 [ 0.]
 [ 0.]
 [ 0.]]
w: 
 [[0.]]
>> Problema canonizado! x:  [0. 0. 0. 1. 2. 6.]

2. Teste de otimalidade (c_N <= 0):
Não passou no teste...

>> c_N: 
[[ 2.]
 [ 1.]
 [-1.]]

3. Seleciona k em N tal que c[k] > 0...
>> k: 0

4. Teste de unboundness (A[:,k] <= 0):
Não passou no teste...

>> A[:,k]: 
[-2.  1.  2.]

5. Passo Simplex...
t: [2. 3.]
r: 0
>> x: 
[[2.]
 [0.]
 [0.]
 [5.]
 [0.]
 [2.]]

6. Atualizando a base...
[3 4 5]
Adicionando o elemento k (k = 0):
[3 4 5 0]
Removendo o r-ésimo elemento (r = 0):
[4 5 0]
>> B: 
[4 5 0]

>>> Iteração 1:

1. Reescrevendo o PL na forma canonica para a base B...

A: 
 [[ 0.  -0.5  0.5  0.5  1.   0. ]
 [ 0.  -2.   0.   1.   0.   1. ]
 [ 1.  -0.5 -0.5 -0.5  0.   0. ]]
b: 
 [[ 2.5]
 [ 7. ]
 [-0.5]]
c: 
 [[0.]
 [2.]
 [0.]
 [1.]
 [0.]

#### Exercício 6

Adicionamos 2 variáveis $x_5, x_6$ para substituirmos o $\geq \rightarrow =$

In [289]:
c = np.array([1,2,3,2,0,0]).reshape(6,1)
A = np.array([[1,2,2,1,1,0],
             [0,1,1,2,0,1]])
b = np.array([6,10]).reshape(2,1)

Passando o problema para a forma padrão, identificamos a base $B=\{5,6\}$

In [290]:
B = np.array([4,5])

In [291]:
%load_ext autoreload
%autoreload 2
from two_phase import simplex_two_phase

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [292]:
S = simplex_two_phase.Simplex(A, c, b, B)

In [293]:
x = S.fase_2()



FASE II:

>>> Iteração 0:

1. Reescrevendo o PL na forma canonica para a base B...

A: 
 [[1. 2. 2. 1. 1. 0.]
 [0. 1. 1. 2. 0. 1.]]
b: 
 [[ 6.]
 [10.]]
c: 
 [[1.]
 [2.]
 [3.]
 [2.]
 [0.]
 [0.]]
w: 
 [[0.]]
>> Problema canonizado! x:  [ 0.  0.  0.  0.  6. 10.]

2. Teste de otimalidade (c_N <= 0):
Não passou no teste...

>> c_N: 
[[1.]
 [2.]
 [3.]
 [2.]]

3. Seleciona k em N tal que c[k] > 0...
>> k: 0

4. Teste de unboundness (A[:,k] <= 0):
Não passou no teste...

>> A[:,k]: 
[1. 0.]

5. Passo Simplex...
t: [ 6. inf]
r: 0
>> x: 
[[ 6.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [10.]]

6. Atualizando a base...
[4 5]
Adicionando o elemento k (k = 0):
[4 5 0]
Removendo o r-ésimo elemento (r = 0):
[0 5]
>> B: 
[0 5]

>>> Iteração 1:

1. Reescrevendo o PL na forma canonica para a base B...

A: 
 [[1. 2. 2. 1. 1. 0.]
 [0. 1. 1. 2. 0. 1.]]
b: 
 [[ 6.]
 [10.]]
c: 
 [[ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 0.]]
w: 
 [[6.]]
>> Problema canonizado! x:  [ 6.  0.  0.  0.  0. 10.]

2. Teste de otimalidade (c_N <= 

/Users/fernandascovino/Documents/PO1/github/simplex/two_phase/simplex_two_phase.py:137: RuntimeWarning: divide by zero encountered in true_divide
  t_set = np.array([self.b[i]/self.A[i, self.k] for i in range(rows)])


In [294]:
np.dot(A, x.reshape(x.shape[0], 1)) == b

array([[ True],
       [ True]])

In [295]:
np.dot(c.T, x)

array([11.33333333])