## Lista 2
----

- Sec.2.1 (certificados): ~~1a, 1b~~, 1c, 1d, 2i, 2ii

- Sec 2.2 (forma padrão): 1a, 1b

- Sec 2.3 (iteração Simplex): 1a, 1b

- Sec 2.4 (Bases e Forma canônica): 1a, 1b, 1c, 1d, 2a, 2b, 3, 4,a, 4b, 4c, 4d, 5a, 5b, 5c, 5d, 5e

- Sec 2.5 (Simplex): 1a, 1b, 2a, 2b, 3, 4, 5, 6a, 6b, 6c

- Sec 2.6 (Simplex 2 fases): 1a, 1b, 1c, 1d, 1e

In [3]:
import numpy as np

### Seção 2.1

#### Exercício 1
(a) 

Provar que o problema é infactível

In [4]:
A = np.array([[3, 5, 6], [1, 3, 4], [-1, 1, -1]])

In [5]:
b = np.array([4, 2, 1]).reshape(3, 1)

Queremos $y$ tal que:

$\text{(i) } y^{T} A \geq \vec{0}^{T},$

$\text{(ii) } y^{T} b < 0$

In [6]:
y = np.array([1, 1, -7])

In [7]:
np.dot(y.T, A) # (i)

array([11,  1, 17])

In [8]:
np.dot(y.T, b) # (ii)

array([-1])

(b) 

Provar que o problema é ilimitado

In [9]:
A = np.array([[1, 0, 1, -1], 
              [0, 1, 2, -1]])

In [10]:
b = np.array([1, 2]).reshape(2, 1)

In [11]:
c = np.array([0, 0, -1, 1]).reshape(4, 1)

Queremos $x = x' + dt : Ax = b, \forall t$ tal que:

$\text{(i) } d > 0$

$\text{(ii) }c^T d \geq 0 \rightarrow d_3 < d_4$

$\text{(iii) }Ad = 0 \rightarrow d_1 + 2 d_3 = 0$

In [12]:
d = np.array([2, 1, 1, 3]).reshape(4, 1) # (i) d > 0
d

array([[2],
       [1],
       [1],
       [3]])

In [13]:
np.dot(c.T, d) # (ii) c'd > 0

array([[2]])

In [14]:
np.dot(A, d) # (iii) Ad = 0

array([[0],
       [0]])

Logo, $x = x' + dt$ é:

In [15]:
x_ = np.array([0, 0, 1, 0]).reshape(4, 1)
x_

array([[0],
       [0],
       [1],
       [0]])

In [16]:
np.dot(A, x_) == b

array([[ True],
       [ True]])

Logo, temos $x = [0, 0, 1, 0] + [2, 1, 1, 3]t$.

(c)

In [17]:
A = np.array([[4, 2, 1, -6, -1], [-1, 1, -4, 1, 3], [3, -6, 5, 3, -5]])

In [18]:
b = np.array([11, -2, -8]).reshape(3, 1)

In [19]:
c = np.array([1, -2, 1, 1, 1]).reshape(5, 1)

In [20]:
d = np.array([1, 1, 1, 1, 1]).reshape(5, 1)

In [21]:
np.dot(c.T, d) # (ii) c'd > 0

array([[2]])

In [22]:
np.dot(A, d) # (iii) c'd > 0

array([[0],
       [0],
       [0]])

In [23]:
x_ = np.array([1, 3, 1, 0, 0]).reshape(5, 1)

In [24]:
np.dot(A, x_)

array([[ 11],
       [ -2],
       [-10]])

In [25]:
x_ = x_ - d
x_

array([[ 0],
       [ 2],
       [ 0],
       [-1],
       [-1]])

In [26]:
np.dot(A, x_)

array([[ 11],
       [ -2],
       [-10]])

(d)

In [28]:
A = np.array([[4, 2, 1, -6, -1], [-1, 1, -4, 1, 3], [3, -6, 5, 3, 5]])

In [29]:
A

array([[ 4,  2,  1, -6, -1],
       [-1,  1, -4,  1,  3],
       [ 3, -6,  5,  3,  5]])

In [30]:
b = np.array([11, -2, -8]).reshape(3, 1)
b

array([[11],
       [-2],
       [-8]])

In [31]:
c = np.array([1, -2, 1, 1, 1]).reshape(5, 1)
c

array([[ 1],
       [-2],
       [ 1],
       [ 1],
       [ 1]])

In [32]:
x = np.array([1, 2, 3, 4, 5]).reshape(5, 1)
x

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [33]:
np.dot(c.T, x)

array([[9]])

### Seção 2.2

#### Exercício 1

Primeiro, temos que converter o problema de minimização para maximização:

In [34]:
c = np.array([2, -1, 4, 2, 4])

In [35]:
c = -c
c

array([-2,  1, -4, -2, -4])

Precisamos garantir que todas as variáveis estão restritas:

$x_3 \rightarrow x_3^{+}, x_3^{-}$;
$x_5 \rightarrow x_5^{+}, x_5^{-}$

$x_3^{+}, x_3^{-}, x_5^{+}, x_5^{-} > 0$

Agora, precisamos mudar as restrições de $\geq, \leq$ para $=$: