In [301]:
import numpy as np
from numpy.linalg import inv

# class LinearProgram():

#     def __init__(self):
#         self.restrictions = np.nan
#         self.costs = np.nan
#         self.independent_cost = 0
#         self.result = np.nan
#         self.basis = np.nan
#         self.operator = max

#     # Provar que o problema é factível! (E achar a base)
#     def find_basis(self):

#         #print("\nCalculando uma base para o PL...")
#         #self.base = np.where(self.costs == 0)[0]
#         pass

class Simplex:

    """
    Instancia o metodo Simplex.

    Parameters
    ----------
    PL : class LinearProgram
        Problema linear definido pela classe LinearProgram

    Return
    ------
    x : np.array
        Solucao otima do PL (nx1).
    """
    def __init__(self, A, c, b, maximum=True, w=0, B=np.nan):

        self.A = A
        self.c = c
        self.b = b
        self.w = w
        
        if type(B) == np.ndarray:
            self.B = B
            self.N = list(set(range(self.A.shape[1])) - set(self.B))
            
        if maximum:
            self.operator = max
        else:
            self.operator = min

    def find_basis(self):

        # Criamos n novas variáveis
        n = A.shape[0]
        A_aux = np.identity(n)
        c = np.ones(n)

        # calculaamos com as novas variáveis referentes à base?
        #self.calculate()
    
    def canonical_form(self):

        # 1. A_B deve ser a matriz identidade
        # 2. c_B = 0
        
        if self.c[self.B].any() != 0 or (self.A[:, self.B] != np.identity(len(self.B))).any():
            self.y = np.linalg.inv(self.A[:, B].T).dot(self.c[B])
            print(self.c)
            self.c = self.c.T - self.y.dot(self.A)
            print(self.c)
            self.w = self.w + self.y.dot(self.b)
            self.A = np.linalg.inv(self.A[:, B]).dot(self.A)
            print(">> Problema canonizado! Indo para (2)...")
            
        else:
            print(">> Problema ja na forma canonica! Indo para (2)...")
    
    def step(self):
        
        x = np.zeros(A.shape[1])
        x[B] = np.linalg.solve(A[:, B], b).T
        
        var_basicas = self.c[x > 0]
        var_nao_basicas = self.c[x == 0]
        
        # Encontrar tamanho do passo
        rows = self.b.shape[0]
        
        t_set = np.array([self.b[i]/self.A[i, self.k] for i in range(rows)])
        t = t_set[t_set > 0] # t > 0
        
        if self.operator:
            t = min(t) # problema de maximizacao
        else:
            t = max(t) # problema de minimizacao
            
        self.r = np.where(t_set == t)[0][0]

        # Dar o passo escolhido
        x_aux = self.b - t*self.A[:, self.k]

        x = np.zeros((var_nao_basicas.shape[0], 1))
        x[self.k, 0] = t
        self.x = np.concatenate((x, x_aux))
        print('>> x == {}'.format(self.x))

    def calculate(self):

        print(">>> Iniciando Simplex!")

        while self.c[self.N].any() > 0:
            
            print("1. Reescrevendo o PL na forma canonica para a base B...\n")
            self.canonical_form()
            
            print("\n2. Teste de otimalidade (c_N <= 0):")
            print(">> c_N == {}".format(self.c[self.N]))

            print("\n3. Seleciona k em N tal que c[k] > 0...")
            # self.k = np.argmax(self.c)
            self.k = self.c.nonzero()[0][0] # primeiro valor não nulo
            print(">> k == {}".format(self.k))

            print("\n4. Teste de unboundness (A[:,k] <= 0):")
            if self.A[:, self.k].any() <= 0:
                (">>> Processo terminado!")
                return x
            print(">> A[:,k] == {}".format(self.A[:, self.k]))
            
            print("\n5. Passo Simplex...")
            self.step()

            print("\n6. Atualizando a base...")
            self.B = np.append(self.B, self.k)
            self.B = np.delete(self.B, self.r)
            
            self.N = list(set(range(self.A.shape[1])) - set(self.B))
            print(">> B == {}\n".format(self.B))

        print("Processo terminado!")
        return x

In [302]:
# Formato do PL: max{z = cx + w : Ax = b, x >= 0}
A = np.matrix([[1,1,1,0,0], [2,1,0,1,0], [-1,1,0,0,1]])
c = np.array([2,3,0,0,0])
b = np.array([6,10,4]).reshape(3,1)
B = np.array([2,3,4])

x = Simplex(A, c, b, B=B)
#x.find_basis()
x.calculate()

>>> Iniciando Simplex!
1. Reescrevendo o PL na forma canonica para a base B...

>> Problema ja na forma canonica! Indo para (2)...

2. Teste de otimalidade (c_N <= 0):
>> c_N == [2 3]

3. Seleciona k em N tal que c[k] > 0...
>> k == 0

4. Teste de unboundness (A[:,k] <= 0):
>> A[:,k] == [[ 1]
 [ 2]
 [-1]]

5. Passo Simplex...
>> x == [[5.]
 [0.]
 [1.]
 [0.]
 [9.]]

6. Atualizando a base...
>> B == [2 4 0]

1. Reescrevendo o PL na forma canonica para a base B...

[2 3 0 0 0]
[[2. 3. 0. 0. 0.]]
>> Problema canonizado! Indo para (2)...

2. Teste de otimalidade (c_N <= 0):


IndexError: index 1 is out of bounds for axis 0 with size 1

In [210]:
np.where(c == 3)[0][0]

1

In [241]:
c[1]

3

In [259]:
np.append(B, 0)

array([2, 3, 4, 0])

In [248]:
np.delete(B, 1)

array([2, 4])